### PR TITLE
Fix custom banner on 1.7

### PR DESCRIPTION
**Pull request by stbenjam**
This plugin is really great, thanks! I couldn't get this to work correctly on 1.7 (see trace), for some reason the decorator wasn't loading, but you can just reference Foreman settings as a hash anyway and that works for me.

```
undefined local variable or method `custom_banner_enabled' for #<#<Class:0x007fd62a55dc20>:0x007fd62a57bab8>

app/views/home/_topbar.html.erb:1:in `_4a04df1ea0bdcfdc8699e64aae28f574'
actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
deface (0.9.1) lib/deface/action_view_extensions.rb:37:in `render'
actionpack (3.2.21) lib/action_view/renderer/partial_renderer.rb:265:in `render_partial'
actionpack (3.2.21) lib/action_view/renderer/partial_renderer.rb:238:in `block in render'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/partial_renderer.rb:237:in `render'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:41:in `render_partial'
actionpack (3.2.21) lib/action_view/helpers/rendering_helper.rb:27:in `render'
haml (4.0.6) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
app/views/layouts/base.html.erb:43:in `_44e877435a61e3bdbaf78e60f4e9537a'
actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
deface (0.9.1) lib/deface/action_view_extensions.rb:37:in `render'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.21) lib/action_view/helpers/rendering_helper.rb:24:in `render'
haml (4.0.6) lib/haml/helpers/action_view_mods.rb:12:in `render_with_haml'
app/views/layouts/application.html.erb:27:in `_3ca01412b2b9c5ac6180f2bb96071a8a'
actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
deface (0.9.1) lib/deface/action_view_extensions.rb:37:in `render'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:59:in `render_with_layout'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/home/stbenjam/.rvm/rubies/ruby-1.9.3-p448/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
actionpack (3.2.21) lib/action_controller/metal/mime_responds.rb:196:in `respond_to'
app/controllers/dashboard_controller.rb:6:in `index'
actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.21) lib/active_support/callbacks.rb:671:in `block (4 levels) in _run__1377388445606300538__process_action__3547824148671814875__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_9390'
activesupport (3.2.21) lib/active_support/callbacks.rb:326:in `around'
activesupport (3.2.21) lib/active_support/callbacks.rb:310:in `_callback_around_8801'
activesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_9390'
activesupport (3.2.21) lib/active_support/callbacks.rb:637:in `block (3 levels) in _run__1377388445606300538__process_action__3547824148671814875__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_9389'
app/controllers/concerns/application_shared.rb:13:in `set_timezone'
activesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_9389'
activesupport (3.2.21) lib/active_support/callbacks.rb:636:in `block (2 levels) in _run__1377388445606300538__process_action__3547824148671814875__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_9388'
app/models/concerns/foreman/thread_session.rb:33:in `clear_thread'
activesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_9388'
activesupport (3.2.21) lib/active_support/callbacks.rb:448:in `block in _run__1377388445606300538__process_action__3547824148671814875__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:215:in `block in _conditional_callback_around_9387'
activesupport (3.2.21) lib/active_support/callbacks.rb:326:in `around'
activesupport (3.2.21) lib/active_support/callbacks.rb:310:in `_callback_around_13'
activesupport (3.2.21) lib/active_support/callbacks.rb:214:in `_conditional_callback_around_9387'
activesupport (3.2.21) lib/active_support/callbacks.rb:414:in `_run__1377388445606300538__process_action__3547824148671814875__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
bullet (4.14.1) lib/bullet/rack.rb:12:in `call'
apipie-rails (0.2.6) lib/apipie/extractor/recorder.rb:97:in `call'
apipie-rails (0.2.6) lib/apipie/middleware/checksum_in_headers.rb:27:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
lib/middleware/catch_json_parse_errors.rb:9:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__2666415137855438532__call__901162450806078856__callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
/home/stbenjam/katello/lib/katello/middleware/silenced_logger.rb:29:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
railties (3.2.21) lib/rails/engine.rb:484:in `call'
railties (3.2.21) lib/rails/application.rb:231:in `call'
railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
rack (1.4.5) lib/rack/builder.rb:134:in `call'
rack (1.4.5) lib/rack/urlmap.rb:64:in `block in call'
rack (1.4.5) lib/rack/urlmap.rb:49:in `each'
rack (1.4.5) lib/rack/urlmap.rb:49:in `call'
rack (1.4.5) lib/rack/content_length.rb:14:in `call'
railties (3.2.21) lib/rails/rack/log_tailer.rb:17:in `call'
puma (2.10.2) lib/puma/server.rb:492:in `handle_request'
puma (2.10.2) lib/puma/server.rb:363:in `process_client'
puma (2.10.2) lib/puma/server.rb:254:in `block in run'
puma (2.10.2) lib/puma/thread_pool.rb:101:in `call'
puma (2.10.2) lib/puma/thread_pool.rb:101:in `block in spawn_thread'
logging (1.8.2) lib/logging/diagnostic_context.rb:323:in `call'
logging (1.8.2) lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
```

### CODE REVIEW

**Comment by jcmcken** [comment]
Hi, thanks for the PR. I don't have a `1.7` instance set up anywhere, but let me give this a test on earlier versions.

**Comment by stbenjam** [comment]
Hey thanks - I actually meant to comment back here, I'm not sure if this is the problem.  Maybe it's something funky with rails autoloading, and the custom banner still mysteriously stops working sometimes with the above error.

**Comment by jcmcken** [comment]
In any case, I like your solution for referencing settings (assuming it works). Seems much simpler than what I did. You can tell I don't really do much Rails
